#!/usr/bin/env bash

db="dns2"

dropdb $db
createdb $db
psql $db -f dns.dd

psql $db -c "insert into view (viewid, name) values (-1, 'unknown');"
psql $db -c "insert into view (viewid, name) values ( 0, '');"
psql $db -c "insert into view (viewid, name) values ( 1, 'master');"
psql $db -c "insert into view (viewid, name) values ( 2, 'internal');"
psql $db -c "insert into view (viewid, name) values ( 3, 'dhhs');"
psql $db -c "insert into view (viewid, name) values ( 4, 'ahe');"

psql $db -c "insert into server (name, address) values ('vm2', '10.112.138.240');"
psql $db -c "insert into server (name, address) values ('u262', '151.178.221.67');"
