#!/usr/bin/perl -w

use strict;
use English;

use DBI;

#use lib '/home/kevinp/src/P5-Net-DNS/lib';

use Net::DNS;
use Net::DNS::Nameserver;
use Net::DNS::Resolver;
use Net::DNS::RR::SOA;
use Net::DNS::RR::TSIG;

use Data::Dumper;

my $verbose = 0;
$verbose = 1; # uncomment for debugging

my $hasixfr = 0;
my $hasiterator = 0;

my $keydir = '/etc/named.d/keys';

# The list of record types we want to keep in the database.
#   Don't mention SOA records here; they're treated specially.

my @RRtypes = qw(a cname mx ns ptr srv txt);

my $db = 'dns2';

if($#ARGV >= 0) {
  for my $arg (@ARGV) {
    my ($zone, $view) = split ':', $arg;
    $view //= 'unknown';
    if ($zone eq 'all') {
      my @zones;
      my $dbh = DBI->connect("dbi:Pg:dbname=$db", '', '', {AutoCommit => 0});
      my $sth = $dbh->prepare("SELECT zone.name, view.name
                               FROM zone, view
                               WHERE zone.view = view.viewid
                                 AND zone.deleted IS NULL
                               ORDER BY zone.name, view.name;
                              ");
      $sth->execute();
      while(my @row = $sth->fetchrow_array()) {
        my ($zone, $view) = @row;
        push @zones, "$zone $view";
      }
      $dbh->disconnect;
      for my $zone (@zones) {
        print $zone, "\n";
        update_zone($zone);
      }
    } else {
      $zone =~ s/\.*$/./;
      update_zone("$zone $view");
    }
  }
  exit 0;
}

my $readpipe;
my $writepipe;

sub query_handler {
  my ($qname, $qclass, $qtype, $peerhost,$query,$conn) = @_;
  my ($rcode, @ans, @auth, @add);

  print "Received query from $peerhost to ". $conn->{sockhost}. "\n";
  $query->print;

  return ('NOTIMP', \@ans, \@auth, \@add);
}

sub notify_handler {
  my ($qname, $qclass, $qtype, $peerhost,$query,$conn) = @_;
  my ($rcode, @ans, @auth, @add);

  print "Received notify from $peerhost to ". $conn->{sockhost}. "\n" if $verbose;
  $query->print if $verbose;

  my $view = 'unknown';
  for my $rr ($query->additional) {
    $view = $rr->name if $rr->type eq 'TSIG';
  }
  print $writepipe "$qname $view\n";
  $rcode = 'NOERROR';

  return ($rcode, \@ans, \@auth, \@add);
}

pipe $readpipe, $writepipe;

my $childid = fork();

if ($childid) { # parent process -- wait for notify and send details to child
  close $readpipe;
  my $ofh = select $writepipe;
  $| = 1;
  select $ofh;
  #print $writepipe "parent here:\n";
  my $ns = new Net::DNS::Nameserver(
                 LocalPort     => 53,
                 ReplyHandler  => \&query_handler,
                 NotifyHandler => \&notify_handler,
                 Verbose       => 1,
               ) or die "Couldn't create name server object\n";
# Drop privilege (should be configurable)
  $UID = 1000;
  $GID = 100;
  $ns->main_loop;
  close $writepipe;
} else { # child process -- perform zone transfers and update database
  close $writepipe;
# Drop privilege (configurable?)
  $UID = $EUID = 1000;
  $GID = $EGID = 100;
  while(my $zone = <$readpipe>) {
    chomp $zone;
    $zone =~ s/\.*$/./; # Canonicalise zone name
    update_zone($zone);
  }
  close $readpipe;
}

sub get_viewid {
  my $view = shift;
  my $dbh = shift;
  my $viewid = 0;

  return 0 unless $view;
 
  print "View: \"$view\"\n" if $verbose;

# This would be nice, but requires Postgresql 9.5
#
#  my $sth = $dbh->prepare("INSERT INTO view (name)
#                           VALUES (?)
#                           ON CONFLICT DO NOTHING
#                           RETURNING viewid");

  my $sth = $dbh->prepare("SELECT viewid
                           FROM   view
                           WHERE  name = ?
                          ");
  $sth->execute($view);
  while(my @row = $sth->fetchrow_array()) {
    $viewid = $row[0];
  }
  $viewid;
}

# This is where all the real work is done

sub update_zone {
  my $args = shift;
  print "update_zone - args: \"$args\"\n" if $verbose;
  my ($zone, $view) = split ' ', $args;
  $zone =~ s/\.*$/./; # Canonicalise again!
  $view //= 'unknown';
  $view =~ s/\.*$//; # remove any trailing dots

# open database
  my $dbh = DBI->connect("dbi:Pg:dbname=$db", '', '', {AutoCommit => 0});

# get zone information
  my $sth = $dbh->prepare("SELECT zoneid
                           FROM   zone, view
                           WHERE  zone.name = ?
                             AND  view.name = ?
                             AND  zone.view = view.viewid
                             AND  deleted IS NULL
                          ");
  $sth->execute($zone, $view);
  my $zoneid = 0;
  while (my @row = $sth->fetchrow_array()) {
    $zoneid = $row[0];
  }

  if ( ! $zoneid ) { # zone isn't in database yet
print "Couldn't find zone id for view $view of $zone\n";
    populate_new_zone($zone, $view, $dbh);
  } else {
print "zoneid is $zoneid\n";
    update_existing_zone($zone, $view, $zoneid, $dbh);
  }

  $dbh->disconnect();
}

sub make_iterator {
  my @rrs = @_;
  print "RRs are ", Dumper(\@rrs), "\n" if $verbose;
  print scalar @rrs, " RRs\n";
  return sub { shift @rrs; };
}

sub populate_new_zone {
  my $zone = shift;
  my $view = shift;
  my $dbh = shift;

  print "Populate '$zone'\n" if $verbose;
  my $zoneid = 0;

# Get the view id, making sure it exists
  my $viewid = get_viewid ($view, $dbh);
print "viewid: $viewid\n";

# create entry in zone table; won't contain a lot yet, but we need the zone id
  my $sth = $dbh->prepare("INSERT INTO zone (name, view)
                           VALUES      (?, ?)
                           RETURNING   zoneid
                          ");
  $sth->execute($zone, $viewid);
  while (my @row = $sth->fetchrow_array()) {
    $zoneid = $row[0];
  }
print "zoneid: $zoneid\n";

# fetch data and update tables
  my $soa = undef;
  my $res = new Net::DNS::Resolver(nameservers => ['10.112.138.240']) or die "Could not create resolver\n";
  prepare_db($dbh);
  my $tsig = create Net::DNS::RR::TSIG("$keydir/$view.key");
  $res->tsig($tsig);
  my $nextrr;
  if ($hasiterator) {
    $nextrr = $res->axfr($zone);
  } else {
    my @rrs = $res->axfr($zone);
    $nextrr = make_iterator(@rrs);
  }
  $soa = $nextrr->();
  print "Initial SOA: ", Dumper(\$soa), "\n" if $verbose;
  while(my $rr = $nextrr->()) {
    add_rr($zoneid, $rr);
  }

# update zone table with new zone
  print "Updating soa\n" if $verbose;
  if (defined $soa) {
    $sth = $dbh->prepare("INSERT INTO dns_soa (zone, name, ttl, mname, rname, serial, refresh, retry, expire, minimum)
                          VALUES              (?,    ?,    ?,   ?,     ?,     ?,      ?,       ?,     ?,      ?      )
                         ");
    $sth->execute($zoneid,
                  $zone,
                  $soa->ttl,
                  $soa->mname,
                  $soa->rname,
                  $soa->serial,
                  $soa->refresh,
                  $soa->retry,
                  $soa->expire,
                  $soa->minimum
                 );
  }

# Now commit the data so it's visible
  print "Committing data\n" if $verbose;
  $dbh->commit();
}

sub update_existing_zone {
  my $zone = shift;
  my $view = shift;
  my $zoneid = shift;
  my $dbh = shift;

  print "Updating '$zone' ($view, $zoneid)\n" if $verbose;
# Get the existing SOA as an object
  my $sth = $dbh->prepare("SELECT mname, serial
                           FROM dns_soa
                           WHERE  zone = ?
                             AND  deleted IS NULL
                          ");
  $sth->execute($zoneid);
  my $mname = 'x';
  my $serial = 0;
  while(my @row = $sth->fetchrow_array()) {
    $mname = $row[0];
    $serial = $row[1];
  }
  print "Old serial number: ", $serial, "\n" if $verbose;
# Create an SOA RR with the old serial number we can attach to an IXFR query
  my $soa = new Net::DNS::RR("$zone SOA z x.y $serial 1 1 1 1");

# Make an AXFR/IXFR query
$mname = '10.112.138.240';
  print "Creating new resolver for $mname\n" if $verbose;
  my $resolver = new Net::DNS::Resolver(nameservers => [ $mname ] );
  #my $key = 'yA169e32jTDIYFmZwfa6pw==';
  #my $tsig = Net::DNS::RR->new("master.key. TSIG $key");
  #my $tsig = Net::DNS::RR->new(name => 'master.key',
  #                             type => 'TSIG',
  #                             key  => '/home/kevinp/tmp/key.master'
  #                            );
  my $tsig = create Net::DNS::RR::TSIG("$keydir/$view.key");
#  print Dumper(\$tsig);
  my $resp = $resolver->tsig($tsig);
#print "TSIG respone: $resp\n";
  my $packet = $resolver->query($zone, 'SOA');
#  print Dumper(\$packet);
  if (defined $packet) {
    my @answer = $packet->answer;
print 'Current serial number is ' . $answer[0]->serial . "\n";
    if (@answer and $answer[0]->type eq 'SOA' and $answer[0]->serial == $serial) {
      print "Zone $zone is up to date\n";
      return;
    }
  }
  my $nextrr;
  if ($hasiterator) {
    if ($hasixfr) {
###TODO
    } else {
      #$nextrr = $resolver->axfr($zone);
    }
  } else {
#    my @rrs = $resolver->axfr($zone);
#    $nextrr = make_iterator(@rrs);
  }
  #my $qry = $resolver->query($zone, 'IXFR', $soa); # FIX
  #my $iterator = $resolver->axfr($zone, 'IN');
print "Fetching zone\n";
  $tsig = create Net::DNS::RR::TSIG("$keydir/$view.key");
  $resolver->tsig($tsig);
  my @rrs = $resolver->axfr($zone, 'IN');
  if (scalar @rrs < 1) {
    print $resolver->errorstring(), "\n";
    return;
  }
# Run through each returned RR processing it
  my $state = 0;
  #my $newsoa = &$iterator();
  print "RRs read: ", Dumper(\@rrs), "\n" if $verbose;
  my $newsoa = shift @rrs;
  print "New SOA: :", Dumper(\$newsoa), "\n" if $verbose;
  #my $newserial = $newsoa->serial;
  #if ($newserial != $serial) {
    prepare_db($dbh); # set up all the DB queries
  #  while (my $rr = &$iterator()) {
    for my $rr (@rrs) {
      print "Handling RR: ", Dumper(\$rr), "\n" if $verbose;
      if ($rr->type eq 'SOA') {
        if ($state == 0) { # initial state -- this is an IXFR transfer
          $state = 2;
        } elsif ($state == 1) { # AXFR -- there shouldn't be an SOA here
        } elsif ($state == 2) { # adding -- new state is deleting
          $state = 3;
        } elsif ($state == 3) { # deleting -- new state is adding
          $state = 2;
        } else {
        }
      } else {
        if ($state == 0) { # must be axfr -- process whole zone
          $state = 1;
          set_delete($zoneid, $dbh);
          replace_rr($zoneid, $rr);
        } elsif ($state == 1) { # doing axfr -- treat specially
          replace_rr($zoneid, $rr);
        } elsif ($state == 2) { # deleting
          del_rr($rr);
        } elsif ($state == 3) { # adding
          add_rr($rr);
        } else { # illegal state
        }
      }
    }
  #}
  print "Deleting old entries\n" if $verbose;
  delete_entries($zoneid, $dbh) if $state == 1;

# add the new soa RR
  update_soa($zone, $zoneid, $newsoa, $dbh);

# Now commit the data so it's visible
  $dbh->commit();
}

my $add_a;
my $add_cname;
my $add_mx;
my $add_ns;
my $add_ptr;
my $add_soa;
my $add_srv;
my $add_txt;
my $del_a;
my $del_cname;
my $del_mx;
my $del_ns;
my $del_ptr;
my $del_soa;
my $del_srv;
my $del_txt;
my $keep_a;
my $keep_cname;
my $keep_mx;
my $keep_ns;
my $keep_ptr;
my $keep_soa;
my $keep_srv;
my $keep_txt;
 
sub prepare_db {
  my $dbh = shift;

  $add_a     = $dbh->prepare("INSERT INTO dns_a     (name, zone, ttl, address)
                              VALUES                (?,    ?,    ?,   ?      )
                             ");
  $del_a     = $dbh->prepare("UPDATE dns_a
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  address = ?
                                AND  deleted IS NULL
                             ");
  $keep_a     = $dbh->prepare("UPDATE dns_a
                              SET    pendingdelete = 0
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  address = ?
                                AND  deleted IS NULL
                             ");
  $add_cname = $dbh->prepare("INSERT INTO dns_cname (name, zone, ttl, cname)
                              VALUES                (?,    ?,    ?,   ?    )
                             ");
  $del_cname = $dbh->prepare("UPDATE dns_cname
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  cname = ?
                                AND  deleted IS NULL
                             ");
  $keep_cname = $dbh->prepare("UPDATE dns_cname
                              SET    pendingdelete = 0
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  cname = ?
                                AND  deleted IS NULL
                             ");
  $add_mx    = $dbh->prepare("INSERT INTO dns_mx    (name, zone, ttl, exchange, preference)
                              VALUES                (?,    ?,    ?,   ?,        ?         )
                             ");
  $del_mx    = $dbh->prepare("UPDATE dns_mx
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  exchange = ?
                                AND  preference = ?
                                AND  deleted IS NULL
                             ");
  $keep_mx    = $dbh->prepare("UPDATE dns_mx
                               SET    pendingdelete = 0
                               WHERE  name = ?
                                 AND  zone = ?
                                 AND  ttl = ?
                                 AND  exchange = ?
                                 AND  preference = ?
                                 AND  deleted IS NULL
                              ");
  $add_ns    = $dbh->prepare("INSERT INTO dns_ns    (name, zone, ttl, nsdname)
                              VALUES                (?,    ?,    ?,   ?      )
                             ");
  $del_ns    = $dbh->prepare("UPDATE dns_ns
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  nsdname = ?
                                AND  deleted IS NULL
                             ");
  $keep_ns    = $dbh->prepare("UPDATE dns_ns
                               SET    pendingdelete = 0
                               WHERE  name = ?
                                 AND  zone = ?
                                 AND  ttl = ?
                                 AND  nsdname = ?
                                 AND  deleted IS NULL
                              ");
  $add_ptr   = $dbh->prepare("INSERT INTO dns_ptr   (name, zone, ttl, address, ptrdname)
                              VALUES                (?,    ?,    ?,   ?,       ?       )
                             ");
  $del_ptr   = $dbh->prepare("UPDATE dns_ptr
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  address = ?
                                AND  ptrdname = ?
                                AND  deleted IS NULL
                             ");
  $keep_ptr   = $dbh->prepare("UPDATE dns_ptr
                               SET    pendingdelete = 0
                               WHERE  name = ?
                                 AND  zone = ?
                                 AND  ttl = ?
                                 AND  address = ?
                                 AND  ptrdname = ?
                                 AND  deleted IS NULL
                              ");
  $del_soa   = $dbh->prepare("UPDATE dns_soa
                              SET    deleted = now()
                              WHERE  zone = ?
                                AND  ttl = ?
                                AND  mname = ?
                                AND  rname = ?
                                AND  serial = ?
                                AND  refresh = ?
                                AND  retry = ?
                                AND  expire = ?
                                AND  minimum = ?
                                AND  deleted IS NULL
                             ");
  $add_srv   = $dbh->prepare("INSERT INTO dns_srv   (name, zone, ttl, priority, weight, port, target)
                              VALUES                (?,    ?,    ?,   ?,        ?,      ?,    ?     )
                             ");
  $del_srv   = $dbh->prepare("UPDATE dns_srv
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  priority = ?
                                AND  weight = ?
                                AND  port = ?
                                AND  target = ?
                                AND  deleted IS NULL
                             ");
  $keep_srv   = $dbh->prepare("UPDATE dns_srv
                               SET    pendingdelete = 0
                               WHERE  name = ?
                                 AND  zone = ?
                                 AND  ttl = ?
                                 AND  priority = ?
                                 AND  weight = ?
                                 AND  port = ?
                                 AND  target = ?
                                 AND  deleted IS NULL
                              ");
  $add_txt   = $dbh->prepare("INSERT INTO dns_txt   (name, zone, ttl, txtdata)
                              VALUES                (?,    ?,    ?,   ?      )
                             ");
  $del_txt   = $dbh->prepare("UPDATE dns_txt
                              SET    deleted = now()
                              WHERE  name = ?
                                AND  zone = ?
                                AND  ttl = ?
                                AND  txtdata = ?
                                AND  deleted IS NULL
                             ");
  $keep_txt   = $dbh->prepare("UPDATE dns_txt
                               SET    pendingdelete = 0
                               WHERE  name = ?
                                 AND  zone = ?
                                 AND  ttl = ?
                                 AND  txtdata = ?
                                 AND  deleted IS NULL
                              ");
}

sub set_delete {
  my $zone = shift;
  my $dbh = shift;

  for my $type (@RRtypes) {
    my $sth = $dbh->prepare("UPDATE dns_$type    
                             SET pendingdelete = 1
                             WHERE zone = ?
                               AND deleted IS NULL
                            ");
     $sth->execute($zone);
$dbh->commit(); # temporary only
  }
}

sub delete_entries {
  my $zone = shift;
  my $dbh = shift;

  for my $type (@RRtypes) {
    my $sth = $dbh->prepare("UPDATE dns_$type    
                             SET deleted       = now(),
                                 pendingdelete = 0
                             WHERE zone           = ?
                               AND pendingdelete  = 1
                               AND deleted       IS NULL
                            ");
    $sth->execute($zone);
  }
}

sub name2ip {
  my $name = shift;
#print "name2ip: $name\n";
  $name =~ s/\.in-addr.arpa//i;
#print "name2ip: $name\n";
  my @octets = split /\./, $name;
#print Dumper(\@octets), "\n";
  join '.', reverse @octets;
}

# add the RR to the database

sub add_rr {
  my $zoneid = shift;
  my $rr = shift;

  my $type = $rr->type;
  print "add rr ($type): ", Dumper(\$rr), "\n"; # if $verbose;
  if ($type eq 'A') {
    $add_a->execute($rr->name, $zoneid, $rr->ttl, $rr->address);
  } elsif ($type eq 'CNAME') {
    $add_cname->execute($rr->name, $zoneid, $rr->ttl, $rr->cname);
  } elsif ($type eq 'MX') {
    $add_mx->execute($rr->name, $zoneid, $rr->ttl, $rr->exchange, $rr->preference);
  } elsif ($type eq 'NS') {
    $add_ns->execute($rr->name, $zoneid, $rr->ttl, $rr->nsdname);
  } elsif ($type eq 'PTR') {
    my $address = name2ip $rr->name;
    $add_ptr->execute($rr->name, $zoneid, $rr->ttl, $address, $rr->ptrdname);
  } elsif ($type eq 'SRV') {
    $add_srv->execute($rr->name, $zoneid, $rr->ttl, $rr->priority, $rr->weight, $rr->port, $rr->target);
  } elsif ($type eq 'TXT') {
    $add_txt->execute($rr->name, $zoneid, $rr->ttl, $rr->txtdata);
  } else {
    # just ignore other types (including SOA) -- should probably raise an error somewhere
  }
}

# delete the RR from the database

sub del_rr {
  my $zoneid = shift;
  my $rr = shift;

  if ($rr->type eq 'A') {
    $del_a->execute($rr->name, $zoneid, $rr->ttl, $rr->address);
  } elsif ($rr->type eq 'CNAME') {
    $del_cname->execute($rr->name, $zoneid, $rr->ttl, $rr->cname);
  } elsif ($rr->type eq 'MX') {
    $del_a->execute($rr->name, $zoneid, $rr->ttl, $rr->exchange, $rr->preference);
  } elsif ($rr->type eq 'NS') {
    $del_ns->execute($rr->name, $zoneid, $rr->ttl, $rr->nsdname);
  } elsif ($rr->type eq 'PTR') {
    my $address = name2ip $rr->name;
    $del_ptr->execute($rr->name, $zoneid, $rr->ttl, $address, $rr->ptrdname);
  } elsif ($rr->type eq 'SOA') {
    $del_soa->execute($zoneid,
                      $rr->ttl,
                      $rr->mname,
                      $rr->rname,
                      $rr->serial,
                      $rr->refresh,
                      $rr->retry,
                      $rr->expire,
                      $rr->minimum,
                      $zoneid
                     );
  } elsif ($rr->type eq 'SRV') {
    $del_srv->execute($rr->name, $zoneid, $rr->ttl, $rr->priority, $rr->weight, $rr->port, $rr->target);
  } elsif ($rr->type eq 'TXT') {
    $del_txt->execute($rr->name, $zoneid, $rr->ttl, $rr->txtdata);
  } else {
    # just ignore other types -- should probably raise an error somewhere
  }
}

# ensure the RR is in the database
#
# This is used when doing an AXFR for an existing zone.
#
# It will mark an existing entry to be retained if it already exists
# and matches, otherwise it will insert a new entry.

sub replace_rr {
  my $zoneid = shift;
  my $rr = shift;
  print "replace rr: ", Dumper(\$rr), "\n" if $verbose;

  if ($rr->type eq 'A') {
    print "Updating A record\n" if $verbose;
    if(0 == $keep_a->execute($rr->name, $zoneid, $rr->ttl, $rr->address)) {
      print "Adding new A record -- didn't already exist\n" if $verbose;
      $add_a->execute($rr->name, $zoneid, $rr->ttl, $rr->address);
    }
  } elsif ($rr->type eq 'CNAME') {
    if(0 == $keep_cname->execute($rr->name, $zoneid, $rr->ttl, $rr->cname)) {
      $add_cname->execute($rr->name, $zoneid, $rr->ttl, $rr->cname);
    }
  } elsif ($rr->type eq 'MX') {
    if(0 == $keep_mx->execute($rr->name, $zoneid, $rr->ttl, $rr->exchange, $rr->preference)) {
      $add_mx->execute($rr->name, $zoneid, $rr->ttl, $rr->exchange, $rr->preference);
    }
  } elsif ($rr->type eq 'NS') {
    if(0 == $keep_ns->execute($rr->name, $zoneid, $rr->ttl, $rr->nsdname)) {
      $add_ns->execute($rr->name, $zoneid, $rr->ttl, $rr->nsdname);
    }
  } elsif ($rr->type eq 'PTR') {
    my $address = name2ip $rr->name;
#print "Address: $address\n";
    if(0 == $keep_ptr->execute($rr->name, $zoneid, $rr->ttl, $address, $rr->ptrdname)) {
      $add_ptr->execute($rr->name, $zoneid, $rr->ttl, $address, $rr->ptrdname);
    }
  } elsif ($rr->type eq 'SRV') {
    if(0 == $keep_srv->execute($rr->name, $zoneid, $rr->ttl, $rr->priority, $rr->weight, $rr->port, $rr->target)) {
      $add_srv->execute($rr->name, $zoneid, $rr->ttl, $rr->priority, $rr->weight, $rr->port, $rr->target);
    }
  } elsif ($rr->type eq 'TXT') {
    if(0 == $keep_txt->execute($rr->name, $zoneid, $rr->ttl, $rr->txtdata)) {
      $add_txt->execute($rr->name, $zoneid, $rr->ttl, $rr->txtdata);
    }
  } else {
    # just ignore other types (including SOA) -- should probably raise an error somewhere
  }
}

sub update_soa {
  my $zone   = shift;
  my $zoneid = shift;
  my $soa    = shift;
  my $dbh    = shift;

  my $sth = $dbh->prepare("UPDATE dns_soa
                           SET    deleted = now()
                           WHERE  zone    = ?
                             AND  deleted IS NULL
                          ");
  $sth->execute($zoneid);
  $sth= $dbh->prepare("INSERT INTO dns_soa (zone, name, ttl, mname, rname, serial, refresh, retry, expire, minimum)
                       VALUES              (?,    ?,    ?,   ?,     ?,     ?,      ?,       ?,     ?,      ?      )
                      ");
  $sth->execute($zoneid,
                $zone,
                $soa->ttl,
                $soa->mname,
                $soa->rname,
                $soa->serial,
                $soa->refresh,
                $soa->retry,
                $soa->expire,
                $soa->minimum,
               );
}

exit 0;
